name: Scan session
description: log session
title: "[SCAN] sub-xx_ses-yyy"
labels: [scan]
assignees: 
  - bpinsard
body:
- type: markdown
  attributes:
    value: "# general infos"

- type: checkboxes
  id: setup
  attributes:
    label: Setup
    description: check all the equipment that was set up
    options:
      - label: biopac
      - label: sensimetrics
      - label: eyetracker

- type: textarea
  attributes:
    label: general notes


- type: markdown
  attributes:
    value: "## task-reading"
- type: checkboxes
  attributes:
    label: task-reading completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-reading issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-reading notes

- type: markdown
  attributes:
    value: "## task-listening"
- type: checkboxes
  attributes:
    label: task-listening completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-listening issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-listening notes



- type: markdown
  attributes:
    value: "## task-aliceEn"
- type: checkboxes
  attributes:
    label: task-aliceEn completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-aliceEn issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-aliceEn notes

- type: markdown
  attributes:
    value: "## task-aliceFr"
- type: checkboxes
  attributes:
    label: task-aliceFr completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-aliceFr issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-aliceFr notes
